---
title: "Cricket players"
author: "Tomasz Solis"
date: "19 August 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r libraries, warning=FALSE, message=FALSE}
library(data.table)
library(tidyverse)
library(kableExtra)

```

```{r unzip load overview}
unzip("espn-cricket-players-data.zip")
cricdata<- data.table(read.csv("cricket_data.csv", stringsAsFactors=FALSE))
```

##Top 10 countries ranked by Test Runs scored
```{r missing values 1}
#cleaning the data in Bowling Test Runs
cricdata$BOWLING_Tests_Runs[cricdata$BOWLING_Tests_Runs==""]<-0
cricdata$BOWLING_Tests_Runs[cricdata$BOWLING_Tests_Runs=="-"]<-0
cricdata$BOWLING_Tests_Runs<-as.numeric(cricdata$BOWLING_Tests_Runs)

#cleaning the data in Batting Test Runs
cricdata$BATTING_Tests_Runs[cricdata$BATTING_Tests_Runs==""]<-0
cricdata$BATTING_Tests_Runs[cricdata$BATTING_Tests_Runs=="-"]<-0
cricdata$BATTING_Tests_Runs<-as.numeric(cricdata$BATTING_Tests_Runs)
```

```{r summarising the test runs}
cricdata$Test_Runs_TOTAL <- cricdata$BOWLING_Tests_Runs + cricdata$BATTING_Tests_Runs
```

```{r aggregating by country and show top 10}
aggregate(Test_Runs_TOTAL~COUNTRY,cricdata, sum)%>%
        arrange(desc(Test_Runs_TOTAL))%>%
        setNames(c("Country", "Test Runs"))%>%
        head(n=10)%>%
        kable() %>%
        kable_styling(bootstrap_options = "striped", font_size = 15, full_width = FALSE)
```

##Top players who have played for England in any category

```{r missing values 2}
cricdata$BATTING_Tests_Ave[cricdata$BATTING_Tests_Ave==""]<-0
cricdata$BATTING_Tests_Ave[cricdata$BATTING_Tests_Ave=="-"]<-0
cricdata$BATTING_Tests_Ave<-as.numeric(cricdata$BATTING_Tests_Runs)

cricdata$BATTING_Tests_Inns[cricdata$BATTING_Tests_Inns==""]<-0
cricdata$BATTING_Tests_Inns[cricdata$BATTING_Tests_Inns=="-"]<-0
cricdata$BATTING_Tests_Inns<-as.numeric(cricdata$BATTING_Tests_Inns)
```

```{r filtering 2}
cricdata%>%
        filter(Major.teams %like% "England",
               BATTING_Tests_Ave >=30, 
               BATTING_Tests_Inns>=100)%>%
        select(NAME, Test_Runs_TOTAL)%>%
        arrange(desc(Test_Runs_TOTAL))%>%
        setNames(c("Name", "Test Runs"))%>%
        head(n=10)%>%
        kable() %>%
        kable_styling(bootstrap_options = "striped", font_size = 15, full_width = FALSE)
```    

##Wisden Cricketer of the Year

```{r filtering 3}
cricdata%>%
        filter(grepl("Wisden Cricketer of the Year", AWARDS, fixed = TRUE))%>%
        select("COUNTRY", "Batting.style")->wca
```

```{r awards per country}
wcaPart1<- wca%>%
        group_by(COUNTRY) %>%
        summarise(noOfAwards = length(COUNTRY))%>%
        mutate(percent = round(noOfAwards / sum(noOfAwards)*100,2))%>%
        select(COUNTRY, percent, noOfAwards)
```

```{r Batting style data}
wcaPart2<- as.data.frame(table(wca))
wcaPart2Left<-wcaPart2[wcaPart2$Batting.style == "Left-hand bat",c("COUNTRY", "Freq")]
wcaPart2Right<-wcaPart2[wcaPart2$Batting.style == "Right-hand bat",c("COUNTRY", "Freq")]
#adding proper names for batting style columns
colnames(wcaPart2Left)<-c("COUNTRY", "Left-hand bat")
colnames(wcaPart2Right)<-c("COUNTRY", "Right-hand bat")
```

```{r merging}
merge(wcaPart1, wcaPart2Left, by = "COUNTRY")%>%
        merge(wcaPart2Right, by = "COUNTRY")%>%
        setNames(c("Country", 
                   "percent", 
                   "number of awards", 
                   "Left-hand bat", 
                   "Right-hand bat"))%>%
        arrange(desc(percent))%>%
        kable() %>%
        kable_styling(bootstrap_options = "striped", font_size = 15, full_width = FALSE)
```

##Top 10 Bowling Test Wickets Players

```{r missing values 4}
cricdata$BOWLING_Tests_Wkts[cricdata$BOWLING_Tests_Wkts==""]<-0
cricdata$BOWLING_Tests_Wkts[is.na(cricdata$BOWLING_Tests_Wkts)]<-0
cricdata$BOWLING_Tests_Wkts[cricdata$BOWLING_Tests_Wkts=="-"]<-0
cricdata$BOWLING_Tests_Wkts <- as.numeric(cricdata$BOWLING_Tests_Wkts)
```
```{r top10 4}
cricdata%>%
        select("NAME", "BOWLING_Tests_Wkts", "Bowling.style")%>%
        arrange(desc(BOWLING_Tests_Wkts))%>%
        setNames(c("Name", "Bowling Test Wickets", "Bowling style"))%>%
        head(n=10)%>%
        kable() %>%
        kable_styling(bootstrap_options = "striped", font_size = 15, full_width = FALSE)
```
## Top 5 living English Test Bowlers


```{r top5 5}
cricdata%>%
        filter(Died=="",
               Major.teams %like% "Cambridge University")%>%
        select(c("NAME", "BOWLING_Tests_Wkts"))%>%
        arrange(desc(BOWLING_Tests_Wkts))%>%
        setNames(c("Name", "Bowling Test Wickets"))%>%
        head(n=5)%>%
        kable() %>%
        kable_styling(bootstrap_options = "striped", font_size = 15, full_width = FALSE)
```
